name: Profile Cards

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  cards:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Profile Cards
        uses: seijikohara/profile-cards-action@v0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: kaique456
          cards: overview,lifetime,contributions,languages
          output-dir: assets
          themes: light,dark
          commit: true
